import Head from "next/head";
import Link from "next/link";
import React from "react";

export const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " - Justdial" : "Justdial"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          {" "}
          <nav className="flex h-12 px-4  items-center justify-between shadow-md ">
            <Link href="/">
              <a className="text-lg font-bold">Justdial</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className="px-2">Cart</a>
              </Link>
              <Link href="/login">
                <a className="px-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center">
          <p>Copyright 2022 Justdial</p>
        </footer>
      </div>
    </>
  );
};
